insert into producto (id, name, price ) values (NEXTVAL('hibernate_sequence'), 'Lemonade - Black Cherry, 591 Ml', 104.11);
insert into producto (id, name, price ) values (NEXTVAL('hibernate_sequence'), 'Corn - On The Cob', 214.37);
insert into producto (id, name, price ) values (NEXTVAL('hibernate_sequence'), 'Sage - Fresh', 415.57);
insert into producto (id, name, price ) values (NEXTVAL('hibernate_sequence'), 'Wine - Prem Select Charddonany', 728.14);
insert into producto (id, name, price ) values (NEXTVAL('hibernate_sequence'), 'Veal Inside - Provimi', 921.34);
insert into producto (id, name, price ) values (NEXTVAL('hibernate_sequence'), 'Lettuce - Belgian Endive', 737.94);
insert into producto (id, name, price ) values (NEXTVAL('hibernate_sequence'), 'Soup - Chicken And Wild Rice', 521.26);
insert into producto (id, name, price ) values (NEXTVAL('hibernate_sequence'), 'Veal - Shank, Pieces', 927.46);
insert into producto (id, name, price ) values (NEXTVAL('hibernate_sequence'), 'Wine - Valpolicella Masi', 620.08);
insert into producto (id, name, price ) values (NEXTVAL('hibernate_sequence'), 'Soup - Cream Of Broccoli', 454.63);
insert into producto (id, name, price ) values (NEXTVAL('hibernate_sequence'), 'Mints - Striped Red', 211.34);
insert into producto (id, name, price ) values (NEXTVAL('hibernate_sequence'), 'Pectin', 991.8);
insert into producto (id, name, price ) values (NEXTVAL('hibernate_sequence'), 'Chicken - Leg / Back Attach', 56.35);
insert into producto (id, name, price ) values (NEXTVAL('hibernate_sequence'), 'Vinegar - Tarragon', 6.6);
insert into producto (id, name, price ) values (NEXTVAL('hibernate_sequence'), 'Tomato - Peeled Italian Canned', 2.43);
insert into producto (id, name, price ) values (NEXTVAL('hibernate_sequence'), 'Lamb Shoulder Boneless Nz', 530.3);
insert into producto (id, name, price ) values (NEXTVAL('hibernate_sequence'), 'Wine - Montecillo Rioja Crianza', 409.17);
insert into producto (id, name, price ) values (NEXTVAL('hibernate_sequence'), 'Bag Stand', 916.69);
insert into producto (id, name, price ) values (NEXTVAL('hibernate_sequence'), 'Lambcasing', 170.01);
insert into producto (id, name, price ) values (NEXTVAL('hibernate_sequence'), 'Honey - Lavender', 160.19);
insert into producto (id, name, price ) values (NEXTVAL('hibernate_sequence'), 'Nut - Cashews, Whole, Raw', 14.25);
insert into producto (id, name, price ) values (NEXTVAL('hibernate_sequence'), 'Muffin Batt - Carrot Spice', 100.88);
insert into producto (id, name, price ) values (NEXTVAL('hibernate_sequence'), 'Milk - Chocolate 250 Ml', 17.36);
insert into producto (id, name, price ) values (NEXTVAL('hibernate_sequence'), 'Towel Dispenser', 845.6);
insert into producto (id, name, price ) values (NEXTVAL('hibernate_sequence'), 'Rosemary - Dry', 838.7);
insert into producto (id, name, price ) values (NEXTVAL('hibernate_sequence'), 'Mangostein', 151.06);
insert into producto (id, name, price ) values (NEXTVAL('hibernate_sequence'), 'Wine - Beringer Founders Estate', 79.3);
insert into producto (id, name, price ) values (NEXTVAL('hibernate_sequence'), 'Ice Cream Bar - Oreo Cone', 599.13);
insert into producto (id, name, price ) values (NEXTVAL('hibernate_sequence'), 'Plasticknivesblack', 169.82);
insert into producto (id, name, price ) values (NEXTVAL('hibernate_sequence'), 'Soap - Mr.clean Floor Soap', 663.59);
